config/routes.rb
Rails.application.routes.draw do
  get 'dashboards/index', as: :dashboards
  resources :logins, only: [:new, :create]
  resources :registrations, only: [:new, :create]
  resources :posts, only: [:new, :create, :show, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
    validates :email, presence: true
    validates :password, presence: true
    has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def index
    @user = User.find_by(id: session[:user_id])
    #redirect_to new_login_path unless @user
    @posts = Post.all
  end
end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
  def new
    user = User.find_by(id: session[:user_id])
    redirect_to dashboards_path if user
    @user = User.new
  end

  def create
    @user = User.find_by(login_params)

    if @user
      session[:user_id] = @user.id
      redirect_to dashboards_path
    else
      flash[:alert] = "Email and password doesn't match"
      render :new, status: :unprocessable_entity #→→→→→→→ VER PORQUE O RENDER BUGA
    end
  end 

  private

    def login_params
      params.require(:user).permit(:email, :password)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    def new
        @post = Post.new
    end

    def create
        @post = Post.new(post_params)
        @post.user_id = session[:user_id]

        if @post.save
          flash[:alert] = "Post created"
          redirect_to "/dashboards/index"
        else
          flash[:alert] = "Couldn't save the post"
          render :new, status: :unprocessable_entity
        end
    end

    def show
    end

    def edit
      @post = Post.find_by_id(params[:id])
      if session[:user_id] != @post.user_id
        flash[:alert] = "Logged user is not the owner of the post"
        redirect_to "/dashboards/index"
      end
    end

    def update
      @post = Post.find_by_id(params[:id])
      if session[:user_id] == @post.user_id
        if @post.update(post_params)
          flash[:alert] = "Post updated"
          redirect_to "/dashboards/index"
        else
          flash[:alert] = "Couldn't update the post"
          render :new, status: :unprocessable_entity
        end
      else
        flash[:alert] = "Logged user is not the owner of the post"
        redirect_to "/dashboards/index"
      end
    end
    
    private

    def post_params
      params.require(:post).permit(:title, :body, :user_id)
    end
  end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  def new
    user = User.find_by(id: session[:user_id])
    redirect_to dashboards_path if user
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to new_login_path
    else
      flash[:alert] = "Couldn't save the User"
      render :new, status: :unprocessable_entity
    end
  end

  private

    def user_params
      params.require(:user).permit(:email, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/logins_helper.rb
module LoginsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/views/dashboards/index.html.erb
<h1>Welcome <%= if @user then @user.email end %></h1>
<div>
  <%= if @user then link_to "New post", "/posts/new" end %>
</div>
<h1>Posts</h1>
<br>
<div id="posts">
    <% @posts.each do |post| %>
        <%= render post %>
        <div>
          <%= link_to "Show details", post %>
        </div>
        <br>
    <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Authentication</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div> <%= notice %> </div>
    <div> <%= alert %> </div>
    <%= yield %>
  </body>
</html>

app/views/logins/create.html.erb
<h1>Logins#create</h1>
<p>Find me in app/views/logins/create.html.erb</p>

app/views/logins/new.html.erb
<h1>Log in</h1>

<%= form_with model: @user, url: logins_path do |form| %>
    <div>
        <%= form.label :email %>
        <%= form.email_field :email %>
    </div>

    <div>
        <%= form.label :password %>
        <%= form.password_field :password %>
    </div>
    
    <div>
        <%= form.submit "Log in" %>
    </div>
<% end %>
<div>
  <%= link_to "Sign up here", "/registrations/new" %>
</div>

app/views/posts/_formPost.html.erb
<%= form_with model: @post do |form| %>
    <div>
        <%= form.label :title %>
        <%= form.text_field :title %>
    </div>

    <div>
        <%= form.label :body %>
        <%= form.text_field :body %>
    </div>
    
    <div>
        <%= form.submit %>
    </div>
<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">
  <div>
    <strong>Title:</strong>
    <%= post.title %>
  </div>

  <div>
    <strong>Autor:</strong>
    <%= User.find_by_id(post.user_id).email%>
  </div>
</div>

app/views/posts/edit.html.erb
<h1>Edit post</h1>

<div>
  <%= link_to "Back to dashboard", "/dashboards/index" %>
</div>

<%= render "formPost", person: @post %>

app/views/posts/new.html.erb
<h1>New post</h1>

<div>
  <%= link_to "Back to dashboard", "/dashboards/index" %>
</div>

<%= render "formPost", person: @post %>

app/views/posts/show.html.erb
<% post = Post.find_by_id(params[:id]) %>

<h1> Details screen for: <%= post.title %> </h1>

<h2> Autor: <%= User.find_by_id(post.user_id).email%> </h2>

<%= post.body %>

<div>
  <%= link_to "Back to dashboard", "/dashboards/index" %>
</div>

<% if post.user_id == session[:user_id] then %>
  <div>
    <%= link_to "Edit this post", edit_post_path(post) %>
  </div>
<% end %>